#! /bin/bash
#
# teaweb       TeaWeb agent management
#
# chkconfig: 2345 40 90
# description: TeaWeb agent management

# teaweb agent install dir
INSTALL_DIR=/opt/teaweb/agent

case "$1" in
start)
    ${INSTALL_DIR}/bin/teaweb-agent start
    ;;
stop)
    ${INSTALL_DIR}/bin/teaweb-agent stop
    ;;
restart)
    ${INSTALL_DIR}/bin/teaweb-agent restart
    ;;
status)
    ${INSTALL_DIR}/bin/teaweb-agent status
    ;;
*)
    echo $"Usage: $0 {start|stop|restart|status}"
    exit 2
esac