#! /bin/bash
#
# teaweb       TeaWeb management
#
# chkconfig: 2345 40 90
# description: TeaWeb management

# teaweb install dir
INSTALL_DIR=/opt/teaweb

export TEAROOT=${INSTALL_DIR}

case "$1" in
start)
    ${INSTALL_DIR}/bin/teaweb start
    ;;
stop)
    ${INSTALL_DIR}/bin/teaweb stop
    ;;
restart)
    ${INSTALL_DIR}/bin/teaweb restart
    ;;
reset)
    ${INSTALL_DIR}/bin/teaweb reset
    ;;
*)
    echo $"Usage: $0 {start|stop|restart|reset}"
    exit 2
esac