#! /bin/bash
#
# teaweb       TeaWeb management
#
# chkconfig: 2345 40 90
# description: TeaWeb management

# teaweb install dir
INSTALL_DIR=/opt/teaweb

case "$1" in
start)
    ${INSTALL_DIR}/bin/teaweb start
    ;;
stop)
    ${INSTALL_DIR}/bin/teaweb stop
    ;;
restart)
    ${INSTALL_DIR}/bin/teaweb restart
    ;;
reload)
    ${INSTALL_DIR}/bin/teaweb reload
    ;;
reset)
    ${INSTALL_DIR}/bin/teaweb reset
    ;;
status)
    ${INSTALL_DIR}/bin/teaweb status
    ;;
*)
    echo $"Usage: $0 {start|stop|restart|reload|reset|status}"
    exit 2
esac